server:
  port: 8098

spring:
  application:
    name: mtls-client
  ssl:
    bundle:
      pem:
        default:
          keystore:
            certificate: "/Users/mustafa/test/mtls-client/work/certs/client-default.crt"
            private-key: "/Users/mustafa/test/mtls-client/work/certs/client-default-d.key"
            private-key-password: 12345678
          truststore:
            certificate: "/Users/mustafa/test/mtls-client/work/certs/server.crt"
        rest:
          keystore:
            certificate: "/Users/mustafa/test/mtls-client/work/certs/client.crt"
            private-key: "/Users/mustafa/test/mtls-client/work/certs/client.key"
            private-key-password: 12345678
          truststore:
            certificate: "/Users/mustafa/test/mtls-client/work/certs/rootCA-default.crt"
